ECommerceASP/Models/Categories.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ECommerceASP.Models
{
    public class Categories
    {
        [Key]
        public int? Id { get; set; }

        public string Category { get; set; }

        [Range(0, 99, ErrorMessage ="Quantite doit etre entre {1} et {2}")]
        public decimal TotalNb { get; set; }
   
    }
}

ECommerceASP/Models/Computers.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace ECommerceASP.Models
{
    public class Computers
    {
        [Key]
        public int Reference { get; set; }

        [Required]
        [DisplayName("Computer Name")]
        public string ComputerName { get; set; }

        [Required]
        public bool Disponibility { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        [Range(0, 999999, ErrorMessage = "Value of {0} must be between {1} and {2}.")]
        public decimal Price { get; set; }


        public DateTimeOffset CreatedDate { get; set; } = DateTimeOffset.UtcNow;
        //public DateTime CreatedDate { get; set; } = DateTime.Now;
    }
}

ECommerceASP/Models/ErrorViewModel.cs
namespace ECommerceASP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ECommerceASP/Models/NUser.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ECommerceASP.Models
{
    public class NUser
    {
        [Key]
        public int ID { get; set; }

        [Required]
        [DisplayName("User Name")]
        public string Name { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        [Range(10.00, 999.00, ErrorMessage ="Value of {0} must be between {1} and {2}.")]
        public decimal Price { get; set; }

        public DateTimeOffset CreatedDate { get; set; } = DateTimeOffset.UtcNow;
        //public DateTime CreatedDate { get; set; } = DateTime.Now;

    }
}

ECommerceASP/Controllers/CategoriesController.cs
using ECommerceASP.Data;
using ECommerceASP.Models;
using Microsoft.AspNetCore.Mvc;

namespace ECommerceASP.Controllers
{


    //Inheritance from Controller for HTTP requests handling and responses
    public class CategoriesController : Controller
    {


        /// <summary>
        /// DEPENDENCY INJECTION
        /// </summary>
        /// <param name="db"></param>
        //
        //Constructor that inject AppDbContext
        public CategoriesController(AppDbContext db)
        {
            _db = db;
        }
        //Here, a private readonly field _db is declared to hold an instance of the AppDbContext class.
        //This field will be used to interact with the database in various controller actions.
        private readonly AppDbContext _db; 


        
        public IActionResult Categories()
        {
            IEnumerable<Categories> categoriesList = _db.Categories.ToList(); // Fetch categories from the database
            return View(categoriesList);
        }


        //get
        public IActionResult AddCategory()
        {
            return View();
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddCategory(Categories Category)
        {   
            //Condition (Save)
            if (ModelState.IsValid)
            {
                _db.Categories.Add(Category);
                _db.SaveChanges();
                TempData["successData"] = "created a new Category item !";
                return RedirectToAction("Categories");
            }
            return View(Category);
        }
    }




}

ECommerceASP/Controllers/HomeController.cs
using ECommerceASP.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ECommerceASP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ECommerceASP/Controllers/NUsersController.cs
using ECommerceASP.Data;
using ECommerceASP.Models;
using Microsoft.AspNetCore.Mvc;

namespace ECommerceASP.Controllers
{
    public class NUsersController : Controller
    {

        public NUsersController(AppDbContext db)
        {
            _db = db;
        }
        private readonly AppDbContext _db;  
        

        public IActionResult Index()
        {
            IEnumerable<NUser> UserList = _db.Users.ToList();
            return View(UserList);
        }


        //get
        public IActionResult AddUser()
        {
            return View();
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddUser(NUser user)
        {   
            //Condition (Save)
            if (ModelState.IsValid)
            {
                _db.Users.Add(user);
                _db.SaveChanges();
                TempData["successData"] = "created a new User !";
                return RedirectToAction("Index");
            }
            return View(user);
        }

        //get Edit
        public IActionResult Edit(int? ID )
        {
            if(ID==null || ID==0)
            {
                return NotFound();
            }
            var user = _db.Users.Find(ID);

            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(NUser user)
        {
            //Condition (Save)
            if (ModelState.IsValid)
            {
                _db.Users.Update(user);
                _db.SaveChanges();
                TempData["successData"] = "updated the User !";
                return RedirectToAction("Index");
            }
            return View(user);
        }


        //get Delete
        public IActionResult Delete(int? ID)
        {
            if (ID == null || ID == 0)
            {
                return NotFound();
            }
            var user = _db.Users.Find(ID);

            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteUser(int? ID)
        {
            var user = _db.Users.Find(ID);
            if (user == null)
            {
                return NotFound();
            }
            _db.Remove(user);
            _db.SaveChanges();
            TempData["successData"] = "deleted the User !";
            return RedirectToAction("Index");
        }
    }
}

ECommerceASP/Views/Categories/AddCategory.cshtml
@model Categories
@{
    ViewData["Title"] = "Add Category Item";
}


<form method="post" asp-action="AddCategory">
    <div class="p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add Category Item</h2>
        </div>
    </div>
     
    <div asp-validation-summary="All"></div>

    <div class="mb-3">
            <label for="Category">Category</label>
            <input class="form-control" asp-for="Category"  id="Category" name="Category" />
               <!-- <option value="0">Select Category</option>
                <option value="1">Computers</option>
                <option value="2">Phones and Tablets</option>
                <option value="3">Resaux and Security</option>
                <option value="4">Electric Machines</option>
                <option value="5">Clothes</option>
            </select>
            -->
        </br>

        <label asp-for="TotalNb"></label>
        <input asp-for="TotalNb" class="form-control" />
        <span asp-validation-for="TotalNb" class="text-danger"></span>
        </br>

        <button type="submit" class="btn btn-success" style="width:150px">Save</button>
        <a asp-action="Categories" asp-controller="Categories" class="btn btn-secondary" style="width:150px">Back to Users</a>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
        }

ECommerceASP/Views/Categories/Categories.cshtml
@model IEnumerable<ECommerceASP.Models.Categories>

@{
    ViewData["Title"] = "Categories";
}

<div class="container p-3">

    @if (TempData["successData"] != null)
    {
        <div class="alert alert-dismissible alert-success">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            <strong>Well done!</strong> You successfully @TempData["successData"]
        </div>
    }

    <div class="row pt-4">

        <div class="col-6">
            <h1 class="text-primary">Categories</h1>
        </div>
        <div class="col-6 text-end">
            <h1 class="text-danger">
                <a class="btn btn-outline-primary" asp-controller="Categories" asp-action="AddCategory"><i class="bi bi-person-plus"></i>&nbsp; Add Category Item</a>
            </h1>
        </div>

    </div>

            <table class="table table-borderless">
                <thead>
                    <tr class="table-active">
                        <td><h4 style="color:red">Category</h4></td>
                        <td><h4 style="text-align:center;color:red">Total Nomber</h4></td>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var Per in Model)
                    {
                    <tr class="table-active">
                        <td>@Per.Category</td>
                        <td style="text-align:center" >@Per.TotalNb</td>
                    </tr>
                    }
                </tbody>
                 
            </table>
 
    <br />
</div>

ECommerceASP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ECommerceASP/Views/NUsers/AddUser.cshtml
@model NUser
@{
    ViewData["Title"] = "AddUser";
}


<form method="post">
    <div class="p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add User</h2>
        </div>
    </div>

    <div asp-validation-summary="All"></div>

    <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
        </br>

        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
        </br>

        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
        </br>


        <button type="submit" class="btn btn-success" style="width:150px" >Save</button>
        <a asp-action="Index" asp-controller="NUsers" class="btn btn-secondary" style="width:150px">Back to Users</a>
    </div>

</form>

        @section Scripts {
            <partial name="_ValidationScriptsPartial" />
        }

ECommerceASP/Views/NUsers/Delete.cshtml
@model NUser
@{
    ViewData["Title"] = "Delete";
}


<form method="post" asp-action="DeleteUser">

    <input asp-for="ID" hidden />

    <div class="p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete User</h2>
        </div>
    </div> 

    <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" disabled class="form-control" /> 
        </br>

        <label asp-for="Email"></label>
        <input asp-for="Email" disabled class="form-control" /> 
        </br>

        <label asp-for="Price"></label>
        <input asp-for="Price" disabled class="form-control text-white" /> 
        </br>


        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-action="Index" asp-controller="NUsers" class="btn btn-secondary" style="width:150px">Back to Users</a>
    </div>

</form> 

ECommerceASP/Views/NUsers/Edit.cshtml
@model NUser
@{
    ViewData["Title"] = "Edit";
}


<form method="post">
    <div class="p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit User</h2>
        </div>
    </div>

    <div asp-validation-summary="All"></div>

        <div class="mb-3">

            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
            <br />

            <label asp-for="Email"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
            <br />

            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
            <br />

            <button type="submit" class="btn btn-success" style="width:150px">Save</button>
            <a asp-action="Index" asp-controller="NUsers" class="btn btn-secondary" style="width:150px">Back to Users</a>
        </div>

</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
        }

ECommerceASP/Views/NUsers/Index.cshtml
@model IEnumerable<NUser>
@{
    ViewData["Title"] = "Index";
}


<div class="container p-3">

    @if (TempData["successData"] != null)
    {   
        <div class="alert alert-dismissible alert-success">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Well done!</strong> You successfully @TempData["successData"]
        </div>
    }

    <div class="row pt-4">
        
        <div class="col-6">
            <h1 class="text-primary">Users</h1>
        </div>
        <div class="col-6 text-end">
            <h1 class="text-danger">
                <a class="btn btn-outline-primary" asp-controller="NUsers" asp-action="AddUser"><i class="bi bi-person-plus"></i>&nbsp; Add User</a>
             </h1>
        </div>

    </div>

    <table class="table border-danger" style="width:100%">
        <thead>
            <tr>
                <th class="text-danger">
                    Id
                </th>
                <th class="text-danger">
                    User Name
                </th>
                <th class="text-danger">
                    Email
                </th>
                <th class="text-danger">
                    Price
                </th>
                <th class="text-danger">
                    Creating Date
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
                @foreach (var x in Model)
                {
                    <tr>
                        <td style="padding-top:15px; width:10%">
                        @x.ID
                        </td>
                        <td style="padding-top:15px; width:15%">
                        @x.Name
                        </td>
                        <td style="padding-top:15px; width:30%">
                        @x.Email
                        </td>
                        <td style="padding-top:15px; width:20%">
                        @x.Price
                        </td>
                        <td style="padding-top:15px; width:30%">
                        @x.CreatedDate
                        </td>
                        <td class="d-flex">
                            <a class="btn btn-outline-success" asp-controller="NUsers" asp-action="Edit" asp-route-Id="@x.ID"><i class="bi bi-pen"></i></a>
                            &nbsp;&nbsp;&nbsp;
                            <a class="btn btn-outline-danger" asp-controller="NUsers" asp-action="Delete" asp-route-Id="@x.ID"><i class="bi bi-trash3"></i></a>
                        </td>
                    </tr>
                }
        </tbody>
    </table>

</div>

ECommerceASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Basic CRUD</title>
    <link rel="stylesheet" href="~/css/CybCSS.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerceASP.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Basic CRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        =
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Categories">Categories</a>
                        </li>
                        
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="NUsers" asp-action="index">Users</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ECommerceASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>